# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 21 Mar 2012 09:05:59 +0000
*               @ALL          1
*               @user         8
