<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sun, 25 Mar 2012 17:15:50 +0200
 */

$conf['title'] = 'Demo';
$conf['lang'] = 'zh';
$conf['template'] = 'taratasy';
$conf['license'] = 'cc-by-sa';
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
