<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 21 Mar 2012 09:24:21 +0000
 */

$conf['title'] = 'Demo';
$conf['lang'] = 'zh';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
